version: "3.7"
services: 
    django:
        container_name: django-test
        build: .
        image:  django-server

        stdin_open: true
        tty: true

        volumes: 
            - .:/code
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
