# Generated by Django 3.0.4 on 2020-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200306_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
