# Generated by Django 2.2.6 on 2020-03-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200307_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, unique=True, upload_to='images'),
        ),
    ]
