# Generated by Django 2.2.6 on 2020-03-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200307_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Name of your listing:', max_length=50, unique=True),
        ),
    ]
